defaults: &defaults
  working_directory: ~/reg-suit
  docker:
    - image: regviz/node-xcb
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "/root/gcloud-service-key.json"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: setup GCP
          command: echo $GCLOUD_SERVICE_KEY > /root/gcloud-service-key.json
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Bootstrap packages
          command: yarn run bootstrap
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Test
          command: |
            yarn run test
      - run:
          name: Regression using gh-io components
          command: |
            cd packages/reg-suit-toppage
            npm run regression

  deploy:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "9b:4a:d1:c6:ff:b7:49:b7:b7:bf:24:fb:b1:1e:bc:a6"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn --pure-lockfile
      - run:
          name: Bootstrap packages
          command: yarn run bootstrap
      - run:
          name: Setup git
          command: |
            git config --global user.email "yosuke.kurami@gmail.com"
            git config --global user.name "Quramy"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Build LP
          command: |
            yarn run build:io
      - run:
          name: Deploy
          command: |
            yarn run deploy

workflows:
  version: 2
  reg_build_pipeline:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
